### ISSUE TITLE
Issue with example data

### ISSUE THREAD

**Issue by luoqianhao** [alabamagan/mri_normalization_tools#1]
I'm trying to learn something about the image normalization pipeline of MRI. here I have a little question: why i can't find the './example_data' and  folder when i want to run the example04.

**Comment by alabamagan** [comment]
Hi @luoqianhao, due to ethics reasons, I cannot upload the image data I used. Theoretically, the example will work for any sets of three correctly named nii.gz images, I will try to test it with some public domain data and upload them in a few days.

**Comment by luoqianhao** [comment]
> 

I get it! thanks for your reply. I will try on my datasets.

**Comment by alabamagan** [comment]
I have upload some sample data as of ac51e69. 
Try to fetch them and run the example one-by-one sequentially,
